# Generated by Django 4.0 on 2022-01-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="slug",
            field=models.SlugField(default="tttt"),
            preserve_default=False,
        ),
    ]
