# Generated by Django 4.0 on 2022-01-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_file_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="slug",
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default="sdgsdg"),
            preserve_default=False,
        ),
    ]
